version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: speed_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: speed_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:Admin%40123@postgres:5432/postgres
      PORT: 5000
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: speed_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
